version: '3.9'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/portal_api?schema=public
      JWT_SECRET: change-me
      JWT_EXPIRES_IN: 1d
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: portal_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
